AWSTemplateFormatVersion: "2010-09-09"
Description: IAM452 Sample CloudFormation
Resources:
  SampleIamRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              AWS: "*"
            Action: ["sts:AssumeRole"]
      Path: /
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "dynamodb:Scan"
                  - "dynamodb:Query"
                  - "dynamodb:UpdateItem"
                  - "dynamodb:GetItem"
                  - "dynamodb:DeleteTable"
                Resource: "*"
              # - Effect: Allow
              #   Action:
              #     - "iam:PassRole"
              #   Resource: "arn:aws:iam::*:role/my-sensitive-roles/adminrole452"
